---
#
- name: Create configuration directory
  file:
    path: "{{ goquorum_config_dir }}"
    state: directory
    owner: "{{ goquorum_user }}"
    group: "{{ goquorum_group }}"
    recurse: yes
  become: true

- name: Create data directory
  file:
    path: "{{ goquorum_data_dir }}"
    state: directory
    owner: "{{ goquorum_user }}"
    group: "{{ goquorum_group }}"
    recurse: yes
  become: true

- name: Init the database
  command: "{{goquorum_current_dir}}/geth init --datadir {{goquorum_data_dir}} {{goquorum_genesis_path}}"
  when: goquorum_init_database
